version: "3.9"
services:
  gateway:
    container_name: Gateway
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - '8086:8086'
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest
    networks:
      - warehouse_warehouseNetwork
  rabbitmq:
    container_name: rabbitmq
    image: 'bitnami/rabbitmq:latest'
    ports:
      - '15672:15672'
networks:
  warehouse_warehouseNetwork:
    external: true